### ISSUE TITLE
Responsabilidade do Servidor

### ISSUE THREAD

**Issue by luizfbicalho** [renatogroffe/ASPNETCore7-REST_API-RateLimitingFixedWindow-StatusCode429_ContagemAcessos#1]
@renatogroffe , eu tenho uma visão que a responsabilidade de controlar a quantidade de requisições não deveria ser do servidor WEB? o iis controla isso e não parece ser melhor que dentro do .NET?

Qual a vantagem de fazer no código?

**Comment by renatogroffe** [comment]
Você poderia por exemplo utilizar essa funcionalidade em um teste de integração, simulando o comportamento de muitas requisições e barrando o processamento. Eu, particularmente, faria essa configuração em um API Gateway, aplicando uma Policy com um limite de utilização (algo na mesma linha do que você mencionou). De qualquer forma, meu intuito com o artigo foi mostrando este novo recurso.
